spring:
  application:
    name: bi-backend
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bi
    username: root
    password: 491001
  # Redis 配置
  redis:
    database: 0
    host: 192.168.5.100
    port: 6379
    timeout: 5000
    password: 491001
    lettuce: #lettuce是springboot内置的，如果用jedis还需要导入相应依赖
      pool:
        max-active: 8  #最大连接
        max-idle: 8   #最大空闲连接
        min-idle: 0   #最小空闲连接
        max-wait: 1000ms #连接等待时间
  redisson:
    database: 1
    host: 192.168.5.100
    port: 6379
    timeout: 5000
    password: 491001
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  # rabbitMQ
  rabbitmq:
    host: 192.168.5.100
    port: 5672
    username: root
    password: 491001
    listener:
      type: simple
      simple:
        default-requeue-rejected: false
        acknowledge-mode: manual
server:
  address: 0.0.0.0
  port: 8108
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# openai接口
yuapi:
  client:
    access-key: fzdc59d4n27ubvebcrwjq6zy4wh5c530
    secret-key: 29u96313wc9maxlw02v57javy5c9qlao